name: AM4 Bot Runner

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -fs /usr/bin/chromium-browser /usr/bin/google-chrome
    
    - name: Install Python packages
      run: |
        pip install selenium==4.30.0
    
    - name: Run AM4 Bot
      env:
        AM4_EMAIL: ${{ secrets.AM4_EMAIL }}
        AM4_PASSWORD: ${{ secrets.AM4_PASSWORD }}
      run: |
        python am4-bot.py
