name: AM4 Bot Runner

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:     # Allows manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
        
    - name: Verify installations
      run: |
        echo "Chrome version: $(google-chrome --version)"
        echo "ChromeDriver version: $(chromedriver --version)"
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.30.0
        
    - name: Run AM4 Bot
      env:
        AM4_EMAIL: ${{ secrets.AM4_EMAIL }}
        AM4_PASSWORD: ${{ secrets.AM4_PASSWORD }}
      run: |
        python am4-bot.py
